### ISSUE TITLE
SSL is required when using cleartext authentication

### ISSUE THREAD

**Issue by nadzyah** [jbouzekri/docker-superset-mongo-poc#3]
I've tried to use this project with my DB and I've got an error while adding the database through Superset Web UI:
```
ERROR: (MySQLdb._exceptions.OperationalError) (1759, 'ssl is required when using cleartext authentication')
```

Regardless SQLALCHEMY URI is `mongobi://root:root@poc_ssm_mongo_bi:3307/samples` or `mongobi://poc_ssm_mongo_bi:3307/samples` (without auth) or `mongobi://root:root@172.17.18.83:3307/samples` (172.17.18.83 -- DB server IP), the error occurs.

**Comment by jbouzekri** [comment]
I am not sure I understand your issue. Is the issue with my proof of concept or when trying to reproduce this in your own setup ? This repository is not a project or a software but a proof of concept that mongobi connector allows to query a mongo database with apache superset.

You need to look at the different settings I put in the docker-compose file and/or docker images and reproduce it in your own setup in order to make it work.

For example, I don't understand why you are keeping the hostname `poc_ssm_mongo_bi` if you say that you are trying to reproduce the poc with your own db.

Moreover the error message is pretty clear, it says that you need ssl with cleartext authentication. So you need to connect to mongobi over SSL as mentioned in the important section of my [README file](https://github.com/jbouzekri/docker-superset-mongo-poc#important). In my custom mongobi docker image, i use environment variable to automatically add options and arguments to mongobi on startup. The important variable for exposing mongobi over SSL are : `         CONFIG_MONGO_BI_SSL_MODE: allowSSL` and `CONFIG_MONGO_BI_SSL_PEM_KEY_FILE: /ssl/mongobi.pem`. Of course, you need to provide a certificate.

Look at the docker-compose for more information : 

```
    poc_ssm_mongo_bi:
        image: poc-ssm-mongo-bi
        container_name: poc_ssm_mongo_bi
        build:
            context: ./mongo-bi
        #entrypoint: ['/bin/sh', '-c', 'sleep 100000']
        ports:
            - 3307:3307
        environment:
            CONFIG_MONGO_BI_MONGO_USERNAME: root
            CONFIG_MONGO_BI_MONGO_PASSWORD: root
            CONFIG_MONGO_BI_AUTH: 1
            CONFIG_MONGO_BI_MONGO_URI: mongodb://poc_ssm_mongo:27017
            CONFIG_MONGO_BI_VERY_VERBOSE: 1
            CONFIG_MONGO_BI_SCHEMA_REFRESH_INTERVAL_SECS: 60
            CONFIG_MONGO_BI_SSL_MODE: allowSSL
            CONFIG_MONGO_BI_SSL_PEM_KEY_FILE: /ssl/mongobi.pem
        volumes:
            - ./mongo-bi/ssl:/ssl
```

I am closing as it is not an issue with the PoC but with your setup.
